# Generated by Django 5.0.2 on 2024-03-17 11:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publicacion_post', verbose_name='URL amigable')),
                ('contenido', models.TextField()),
                ('publicacion_post', models.DateTimeField(default=django.utils.timezone.now)),
                ('creacion_post', models.DateTimeField(auto_now_add=True)),
                ('actualizacion_post', models.DateTimeField(auto_now=True)),
                ('status_post', models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado')], default='draft', max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('privacidad', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publicacion_post',),
            },
        ),
    ]
