# Generated by Django 5.0.2 on 2024-03-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_BlogAgri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tema_post',
            field=models.CharField(choices=[('cosechas', 'Cosechas'), ('tecnologia_agricola', 'Tecnología Agrícola'), ('cambio_climatico', 'Cambio Climático y Agricultura'), ('polinizacion', 'Polinización y Agricultura'), ('nutricion_de_suelos', 'Nutrición de Suelos'), ('plagas_y_enfermedades', 'Plagas y Enfermedades en los Cultivos'), ('agroindustria', 'Agroindustria'), ('sostenibilidad_agricola', 'Sostenibilidad Agrícola'), ('mercado_agricola', 'Mercado Agrícola'), ('politicas_agricolas', 'Políticas Agrícolas'), ('general', 'General')], default='General', max_length=50),
        ),
    ]
