# Generated by Django 5.0.2 on 2024-03-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_BlogAgri', '0002_post_tema_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='privacidad',
            new_name='publico',
        ),
    ]
