# Generated by Django 5.0.2 on 2024-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_BlogAgri', '0003_rename_privacidad_post_publico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publico',
        ),
        migrations.AlterField(
            model_name='post',
            name='status_post',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicar')], default='draft', max_length=10, verbose_name='Borrador'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tema_post',
            field=models.CharField(choices=[('cosechas', 'Cosechas'), ('tecnologia_agricola', 'Tecnología Agrícola'), ('cambio_climatico', 'Cambio Climático y Agricultura'), ('polinizacion', 'Polinización y Agricultura'), ('nutricion_de_suelos', 'Nutrición de Suelos'), ('plagas_y_enfermedades', 'Plagas y Enfermedades en los Cultivos'), ('agroindustria', 'Agroindustria'), ('sostenibilidad_agricola', 'Sostenibilidad Agrícola'), ('mercado_agricola', 'Mercado Agrícola'), ('politicas_agricolas', 'Políticas Agrícolas'), ('general', 'General')], default='General', max_length=50, verbose_name='Tema'),
        ),
    ]
