# Generated by Django 5.0.2 on 2024-03-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_BlogAgri', '0004_remove_post_publico_alter_post_status_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status_post',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Público', 'Público')], default='draft', max_length=10, verbose_name='Privacidad'),
        ),
    ]
