# Generated by Django 5.0.2 on 2024-03-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_BlogAgri', '0005_alter_post_status_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status_post',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Público', 'Público')], max_length=10, verbose_name='Privacidad'),
        ),
    ]
