# Generated by Django 5.0.2 on 2024-03-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_BlogAgri', '0006_alter_post_status_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status_post',
            field=models.IntegerField(choices=[('Borrador', 'Borrador'), ('Público', 'Público')], verbose_name='Privacidad'),
        ),
    ]
