# Generated by Django 5.0.2 on 2024-03-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_RiskCalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete_tec',
            name='riesgo',
            field=models.CharField(choices=[('A', 'Alto'), ('B', 'Bajo'), ('M', 'Moderado')], default=None, max_length=200),
        ),
    ]
