# Generated by Django 5.0.2 on 2024-03-05 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_RiskCalc', '0003_ubicacion_paquete_tec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete_tec',
            name='rendimiento_promedio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
