# Generated by Django 5.0.2 on 2024-03-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_RiskCalc', '0005_alter_paquete_tec_hectareas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rfc',
            field=models.CharField(default=None, max_length=13, verbose_name='RFC'),
        ),
    ]
